spring:
  application:
    name: asset
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: asset
    password: password
    url: jdbc:mysql://localhost:3306/asset?useUnicode=true&character_set_server=utf8mb4&useSSL=false
